import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
	title: "Sudheer KT OneGram Gold",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body suppressHydrationWarning>
				{children}
			</body>
		</html>
	);
}
